### ISSUE TITLE
How to avoid producing a specific symbol?

### ISSUE THREAD

**Issue by dridk** [tomerfiliba-org/reedsolomon#84]
I want to generate multiple data blocks with Reed-Solomon error correction. To separate these blocks, I want to use a delimiter byte that does not collide with the correction bytes. Is it possible to "reduce the gallois field " ? For example, avoid encoder to produce the 0xFF bytes ?

**Comment by lrq3000** [comment]
I would instead suggest to encode the output such as base64, any bidirectional mapping will do, so that you can decode backward at any later point with no loss.

Of course this reduces the effectiveness of the error correction.

Or use a galois field smaller than the characters you want to keep out of it.

Otherwise i am not aware of a way to exclude some specific characters in the middle of the field, all such methods are bound to be hacky.

**Comment by dridk** [comment]
Thanks for your suggestion. I will check your mehode with base64.

About the reduction of the gallois field, is it possible to set the RSCodec to 254 symbol instead of 255 ? Or it must be a power of 2.

**Comment by lrq3000** [comment]
Must be a power of 2 with this lib, and I am not aware of any theoretical work on galois field with a "non power of 2", maybe it may be trivial for a maths wizard but for me I can't see how to do it because there are lots of calculations that assume a power of 2 and wouldn't work otherwise (I tried to note that whenever this is the case in the sourcecode).

**Comment by dridk** [comment]
Thank you very much for your help.
i have come up with a third solution. I can replace one byte by two in the following way to remove 0xFF

- replace 0xFF by 0xF10 - 0xF11
- replace 0xF10 by 0xF10 - 0xF12
